# Generated by Django 3.1.4 on 2020-12-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PestControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custname', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(unique=True)),
                ('type_of_pest', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=300)),
            ],
        ),
    ]
